package com.vyibc.codeassistant.services

class PronunciationAssistService {

    // 常见英文单词的中文谐音映射
    private val phoneticMap = mapOf(
        // 基础词汇
        "hello" to "哈喽",
        "world" to "我的",
        "thank" to "三克",
        "you" to "油",
        "please" to "普里兹",
        "sorry" to "搜瑞",
        "welcome" to "维尔康",
        "goodbye" to "古德拜",
        "good" to "古德",
        "morning" to "毛宁",
        "evening" to "衣无宁",
        "night" to "奈特",
        "yes" to "叶斯",
        "no" to "诺",
        "okay" to "欧K",
        "ok" to "欧K",
        "fine" to "发音",
        "great" to "格瑞特",
        "nice" to "奈斯",
        "beautiful" to "比有提否",
        "love" to "拉夫",
        "like" to "来客",
        "want" to "望特",
        "need" to "尼德",
        "know" to "诺",
        "think" to "辛克",
        "see" to "西",
        "look" to "卢克",
        "come" to "康姆",
        "go" to "勾",
        "get" to "盖特",
        "make" to "美克",
        "take" to "忒克",
        "give" to "给夫",
        
        // 编程相关
        "function" to "方克神",
        "class" to "克拉斯",
        "method" to "美索德",
        "variable" to "瓦瑞爱吧",
        "string" to "斯特林",
        "number" to "南伯",
        "boolean" to "布林",
        "array" to "阿瑞",
        "object" to "噢布杰克特",
        "return" to "瑞腾",
        "import" to "音剖特",
        "export" to "艾克斯剖特",
        "public" to "帕布里克",
        "private" to "普来微特",
        "static" to "斯太提克",
        "final" to "发诺",
        "const" to "康斯特",
        "let" to "莱特",
        "var" to "瓦",
        "if" to "衣夫",
        "else" to "艾尔斯",
        "for" to "佛",
        "while" to "歪尔",
        "do" to "杜",
        "switch" to "斯威奇",
        "case" to "开斯",
        "break" to "布瑞克",
        "continue" to "康提牛",
        "try" to "踹",
        "catch" to "凯奇",
        "finally" to "发诺历",
        "throw" to "丝楼",
        "new" to "牛",
        "delete" to "得李特",
        "this" to "地斯",
        "super" to "苏剖",
        "interface" to "音特费斯",
        "extends" to "艾克斯腾兹",
        "implements" to "印普里门茨",
        "abstract" to "阿布斯踹客特",
        "package" to "派开基",
        "null" to "诺",
        "undefined" to "昂得否音德",
        "true" to "出",
        "false" to "佛尔斯",
        
        // 常用动词
        "create" to "克瑞爱特",
        "build" to "比尔德",
        "start" to "斯塔特",
        "stop" to "斯塔普",
        "run" to "软",
        "call" to "考",
        "send" to "森德",
        "receive" to "瑞西夫",
        "open" to "欧盆",
        "close" to "克劳斯",
        "save" to "塞夫",
        "load" to "劳德",
        "update" to "阿普得特",
        "delete" to "得李特",
        "add" to "艾德",
        "remove" to "瑞姆夫",
        "find" to "发音德",
        "search" to "瑟奇",
        "sort" to "搜特",
        "filter" to "菲尔特",
        "map" to "美普",
        "reduce" to "瑞杜斯",
        
        // 数据类型
        "int" to "音特",
        "integer" to "音特基",
        "float" to "佛劳特",
        "double" to "搭布",
        "char" to "恰",
        "byte" to "拜特",
        "long" to "朗",
        "short" to "搜特",
        "list" to "里斯特",
        "set" to "塞特",
        "map" to "美普",
        "hash" to "哈希",
        "tree" to "出",
        "node" to "诺德",
        "edge" to "艾基",
        "graph" to "格拉夫",
        "queue" to "Q",
        "stack" to "斯太克",
        "heap" to "黑普",
        
        // 网络相关
        "http" to "H T T P",
        "https" to "H T T P S",
        "url" to "U R L",
        "api" to "A P I",
        "json" to "杰森",
        "xml" to "X M L",
        "html" to "H T M L",
        "css" to "C S S",
        "javascript" to "加瓦斯克里普特",
        "python" to "拍森",
        "java" to "加瓦",
        "kotlin" to "考特林",
        "swift" to "斯威夫特",
        "go" to "勾",
        "rust" to "拉斯特",
        "typescript" to "态普斯克里普特",
        "react" to "瑞艾克特",
        "vue" to "V",
        "angular" to "安古拉",
        "node" to "诺德",
        "express" to "艾克斯普瑞斯",
        "spring" to "斯普林",
        "boot" to "布特",
        "framework" to "费瑞么沃克",
        "library" to "来不瑞历",
        "module" to "毛丢",
        "component" to "康剖年特",
        "service" to "瑟维斯",
        "controller" to "康出劳拉",
        "model" to "毛豆",
        "view" to "V",
        "template" to "滕普里特",
        "config" to "康费个",
        "setting" to "塞廷",
        "property" to "破婆提",
        "parameter" to "趴拉米特",
        "argument" to "阿古门特",
        "response" to "瑞斯蓬斯",
        "request" to "瑞奎斯特",
        "header" to "黑德",
        "body" to "波弟",
        "status" to "斯太特斯",
        "code" to "考德",
        "message" to "美西基",
        "error" to "艾勒",
        "exception" to "艾克塞普神",
        "warning" to "沃宁",
        "info" to "音否",
        "debug" to "得巴个",
        "log" to "劳个",
        "file" to "发音",
        "folder" to "否得",
        "directory" to "得瑞克特瑞历",
        "path" to "拍斯",
        "name" to "内姆",
        "type" to "泰普",
        "size" to "塞斯",
        "length" to "朗斯",
        "width" to "威斯",
        "height" to "海特",
        "color" to "卡拉",
        "image" to "衣美基",
        "video" to "维弟欧",
        "audio" to "奥弟欧",
        "text" to "忒克斯特",
        "font" to "方特",
        "style" to "斯太尔",
        "theme" to "西姆",
        "layout" to "雷奥特",
        "design" to "得塞音",
        "user" to "有瑟",
        "admin" to "艾德民",
        "account" to "阿考特",
        "profile" to "破否",
        "session" to "塞神",
        "token" to "套肯",
        "key" to "K",
        "value" to "瓦鲁",
        "pair" to "派尔",
        "index" to "音得克斯",
        "item" to "爱谈",
        "element" to "艾里门特",
        "data" to "得塔",
        "base" to "贝斯",
        "table" to "忒吧",
        "column" to "卡拉姆",
        "row" to "劳",
        "field" to "菲尔德",
        "record" to "瑞考德",
        "query" to "奎瑞历",
        "select" to "塞来客特",
        "insert" to "音瑟特",
        "update" to "阿普得特",
        "delete" to "得李特",
        "where" to "威尔",
        "order" to "奥德",
        "by" to "拜",
        "group" to "古鲁普",
        "having" to "哈文",
        "join" to "照音",
        "inner" to "音呢",
        "outer" to "奥特",
        "left" to "来夫特",
        "right" to "来特",
        "union" to "有尼昂",
        "distinct" to "得斯廷克特",
        "count" to "靠特",
        "sum" to "萨姆",
        "avg" to "啊V基",
        "min" to "民",
        "max" to "麦克斯"
    )
    
    /**
     * 获取单词的中文谐音
     */
    fun getChinesePhonetic(word: String): String? {
        val cleanWord = word.trim().lowercase()
        return phoneticMap[cleanWord]
    }
    
    /**
     * 为文本中的英文单词添加中文谐音
     */
    fun addChinesePhoneticToText(text: String): String {
        val words = text.split(Regex("\\s+"))
        val result = StringBuilder()
        
        for (word in words) {
            if (word.matches(Regex("[a-zA-Z]+"))) {
                val phonetic = getChinesePhonetic(word)
                if (phonetic != null) {
                    result.append("$word($phonetic) ")
                } else {
                    result.append("$word ")
                }
            } else {
                result.append("$word ")
            }
        }
        
        return result.toString().trim()
    }
}